### ISSUE TITLE
openapi可否可自定义访问路径 例如server.servlet.context-path前缀

### ISSUE THREAD

**Issue by qinkangdeid** [babyfish-ct/jimmer#416]
# 版本
Jimmer：0.8.86
开发语言：kotlin  1.9.22
springboot：2.7.18
构建工具：maven3

# 问题描述

openapi的访问地址是否可以自定义  例如增加 `server.servlet.context-path`前缀

```yaml
  jimmer:
    client:
     ts:
        path: /ts.zip
     openapi:
        path: /xxxxxx/openapi.yml
        ui-path: /xxxxxx/openapi.html
        properties:
          info:
            title: "Jimmer SQL Example"
            version: "1.0.0"
            description: "This is a example of Jimmer SQL"

```
